{{- if .Values.runner.token }}
{{- $name := include "gitea-runner.name" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "gitea-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.runner.token }}
{{- end }}
